# Generated by Django 3.2.9 on 2021-12-21 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_auto_20211221_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='archer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
