# Generated by Django 3.2.9 on 2022-01-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_alter_score_archer'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
