# Generated by Django 3.2.9 on 2022-01-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0009_alter_profileuser_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='shooting_age',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='rndname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='round', to='score.round'),
        ),
    ]
