# Generated by Django 3.2.9 on 2022-01-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0010_auto_20220108_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='shooting_age',
        ),
    ]
