# Generated by Django 3.2.9 on 2022-01-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0012_alter_score_shootingas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='shootingas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shootingas', to='score.age'),
        ),
    ]
