# Generated by Django 3.2.9 on 2022-01-10 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0014_alter_score_shootingas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='round',
        ),
        migrations.AddField(
            model_name='round',
            name='type',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='score',
            name='shootingas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.age'),
        ),
        migrations.DeleteModel(
            name='RoundType',
        ),
    ]
