# Generated by Django 3.2.9 on 2022-01-14 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0018_score_shootingas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='bowtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bowtype1', to='score.bowtype'),
        ),
        migrations.AlterField(
            model_name='score',
            name='shootingas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shootingas', to='score.age'),
        ),
    ]
