# Generated by Django 3.2.9 on 2022-01-26 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0021_alter_score_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='classid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='bowtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bowtypes', to='score.bowtype'),
        ),
    ]
