# Generated by Django 3.2.9 on 2022-01-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0022_auto_20220126_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='classification',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
