# Generated by Django 3.2.9 on 2022-01-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0026_alter_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='BM',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Bowman'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='GMB',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Grand Master Bowman'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='MB',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Master Bowman'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='first',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='1st Class Bowman'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='second',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='2nd Class Bowman'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='third',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='3rd Class Bowman'),
        ),
    ]
