# Generated by Django 3.2.9 on 2022-01-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0028_score_handicap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handicap_Rotated',
            fields=[
                ('round', models.IntegerField(primary_key=True, serialize=False)),
                ('zero', models.IntegerField(blank=True, default=0, null=True)),
                ('one', models.IntegerField(blank=True, default=0, null=True)),
                ('two', models.IntegerField(blank=True, default=0, null=True)),
                ('three', models.IntegerField(blank=True, default=0, null=True)),
                ('four', models.IntegerField(blank=True, default=0, null=True)),
                ('five', models.IntegerField(blank=True, default=0, null=True)),
                ('six', models.IntegerField(blank=True, default=0, null=True)),
                ('seven', models.IntegerField(blank=True, default=0, null=True)),
                ('eight', models.IntegerField(blank=True, default=0, null=True)),
                ('nine', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
