# Generated by Django 3.2.9 on 2022-01-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0030_auto_20220131_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='handicap_rotated',
            name='round_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
