# Generated by Django 3.2.9 on 2022-01-31 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0032_auto_20220131_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='handicap_rotated',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handicap_rotated',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.round'),
        ),
    ]
