# Generated by Django 3.2.9 on 2021-12-21 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_score_bowtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='score',
            name='dateshot',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Round Shot'),
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='shootingas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='score.age'),
        ),
    ]
