# Generated by Django 3.2.9 on 2022-01-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0015_auto_20220110_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='shootingas',
        ),
    ]
