# Generated by Django 3.2.9 on 2022-01-12 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0016_remove_score_shootingas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='archer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
