# Generated by Django 3.2.9 on 2022-01-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0020_auto_20220125_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='classification',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
