# Generated by Django 3.2.9 on 2022-01-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0023_alter_score_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='classification',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
