# Generated by Django 3.2.9 on 2022-01-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0024_alter_score_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
