# Generated by Django 3.2.9 on 2022-01-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0027_auto_20220128_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='handicap',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
