# Generated by Django 3.2.9 on 2022-01-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0031_handicap_rotated_round_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handicap_rotated',
            name='id',
        ),
        migrations.AlterField(
            model_name='handicap_rotated',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='score.round'),
        ),
    ]
