# Generated by Django 3.2.9 on 2022-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0036_auto_20220218_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='region',
            field=models.CharField(choices=[('E', 'EMAS'), ('W', 'WMAS'), ('S', 'SMAS')], default='', max_length=200),
        ),
    ]
