# Generated by Django 3.2.9 on 2022-02-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0037_auto_20220224_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handicap_rotated',
            name='thrirteen',
        ),
        migrations.AddField(
            model_name='handicap_rotated',
            name='thirteen',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='region',
            field=models.CharField(choices=[('-', '----'), ('NCAS', 'NCAS'), ('EMAS', 'EMAS'), ('GCAS', 'GCAS'), ('WMAS', 'WMAS'), ('SCAS', 'SCAS'), ('Ssottish Archery', 'Scottish Archery'), ('Welsh ARchery', 'Welsh Archery'), ('NI Archery', 'Archery NI')], default='----', max_length=200),
        ),
    ]
