# Generated by Django 3.2.9 on 2022-05-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20220502_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundscore',
            name='scoreid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='score.score'),
            preserve_default=False,
        ),
    ]
