# Generated by Django 3.2.9 on 2022-05-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_roundscore_scoreid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundscore',
            name='tens',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
