# Generated by Django 3.2.9 on 2022-05-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_roundscore_tens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundscore',
            name='archer',
        ),
        migrations.RemoveField(
            model_name='roundscore',
            name='round',
        ),
    ]
