# Generated by Django 3.2.9 on 2022-05-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_auto_20220507_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='eleven',
        ),
        migrations.AlterField(
            model_name='roundscore',
            name='scoreid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
