# Generated by Django 3.2.9 on 2022-05-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_auto_20220522_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundscore',
            name='end_count',
            field=models.IntegerField(default=0),
        ),
    ]
