# Generated by Django 3.2.9 on 2022-05-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0008_round_numberofends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='numberOfEnds',
            field=models.IntegerField(default=0),
        ),
    ]
