# Generated by Django 3.2.9 on 2022-05-26 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0009_alter_round_numberofends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundscore',
            name='shot_1',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
