# Generated by Django 3.2.9 on 2022-05-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0010_alter_roundscore_shot_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundscore',
            name='doz',
            field=models.IntegerField(default=0),
        ),
    ]
