# Generated by Django 3.2.9 on 2022-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0013_auto_20220529_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundscore',
            name='end_1_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundscore',
            name='end_2_counter',
            field=models.IntegerField(default=0),
        ),
    ]
