# Generated by Django 3.2.9 on 2022-06-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0014_auto_20220530_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundscore',
            name='distance_score',
            field=models.IntegerField(default=0),
        ),
    ]
