# Generated by Django 3.2.9 on 2022-06-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0015_roundscore_distance_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundscore',
            name='distance_score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
